=== bernasali/XML-Programming-Project/MyProject/cameras-catalog.dtd
<?xml version="1.0" encoding="UTF-8"?>

        <!ELEMENT catalog (brand_info,cameras)>
        <!ELEMENT cameras (camera+)>
        <!ELEMENT camera (brand_info,model,price,color,image,features,
                physical-specifications,power_supply)>
        <!ELEMENT model (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT color (#PCDATA)>
        <!ELEMENT image (#PCDATA)>
        <!ELEMENT features (effective_pixels,wi-fi,processor,display,video)>
        <!ELEMENT physical-specifications (size,weight)>
        <!ELEMENT power_supply (battery,energy_saving,charger)>
        <!ELEMENT effective_pixels (#PCDATA)>
        <!ELEMENT wi-fi (#PCDATA)>
        <!ELEMENT processor (#PCDATA)>
        <!ELEMENT display (#PCDATA)>
        <!ELEMENT video (#PCDATA)>
        <!ELEMENT size (#PCDATA)>
        <!ELEMENT weight (#PCDATA)>
        <!ELEMENT battery (#PCDATA)>
        <!ELEMENT energy_saving (#PCDATA)>
        <!ELEMENT charger (#PCDATA)>
        <!ELEMENT brand_info (brand,realise_date)>
        <!ELEMENT brand (#PCDATA)>
        <!ELEMENT realise_date (#PCDATA)>

        <!ATTLIST weight w_unit CDATA #REQUIRED>
        <!ATTLIST size s_unit CDATA #REQUIRED>
        <!ATTLIST wi-fi has (Yes|No) "No">
        <!ATTLIST effective_pixels px CDATA #REQUIRED>
        <!ATTLIST price currency CDATA #REQUIRED>
        <!ATTLIST camera
                resistance (water-proof|dust-proof|water-dust-proof) #REQUIRED
                type CDATA #REQUIRED>
        <!ATTLIST video max-duration CDATA #REQUIRED>

=== bernasali/XML-Programming-Project/MyProject/new_xml_5.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet type="txt/xsl" href="xml_html_1.xsl" ?>

<!DOCTYPE catalog SYSTEM "cameras-catalog.dtd">

<catalog>
    <brand_info>
        <brand>Instax</brand>
        <realise_date>10.10.1998</realise_date>
    </brand_info>

    <cameras>
        <camera type="Instant" resistance="dust-proof">
            <brand_info>
                <brand>Instax</brand>
                <realise_date>18.03.2020</realise_date>

            </brand_info>
            <model>mini 11</model>
            <price currency="лв">200</price>
            <color>Лилав</color>
            <image>camera_images/mini11.jpg</image>
            <features>

                <effective_pixels px="мегапиксела">10</effective_pixels>
                <wi-fi has="No"/>
                <processor>DIGIC 4+</processor>
                <display>Оптична тръба</display>
                <video max-duration="00:00">Няма опция за  видео</video>

            </features>

            <physical-specifications>
                <size s_unit="mm">140 x 70 x 130</size>
                <weight w_unit="g">435</weight>

            </physical-specifications>
            <power_supply>
                <battery>Въглерод-Цинкова (R03)</battery>
                <energy_saving>Няма</energy_saving>
                <charger>Батерии</charger>
            </power_supply>


        </camera>

        <camera type="Instant" resistance="dust-proof">

            <brand_info>
                <brand>Instax</brand>
                <realise_date>05.07.2015</realise_date>
            </brand_info>

            <model>Wide 300</model>
            <price currency="лв">267</price>
            <color>Тофи</color>
            <image>camera_images/Wide 300.jpg</image>
            <features>

                <effective_pixels px="мегапиксела"> 10 </effective_pixels>
                <wi-fi has="No"/>
                <processor>DIGIC 4</processor>
                <display>Оптична тръба</display>
                <video max-duration="00:00">Няма опция за  видео</video>

            </features>

            <physical-specifications>
                <size s_unit="mm">167.8 x 120.9 x 94.7</size>
                <weight w_unit="g">612</weight>
            </physical-specifications>

            <power_supply>
                <battery>Въглерод-Цинкова (R03)</battery>
                <energy_saving>Няма</energy_saving>
                <charger>Батерии</charger>
            </power_supply>


        </camera>

    </cameras>

</catalog>

=== bernasali/XML-Programming-Project/MyProject/new_xml_1.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="txt/xsl" href="xml_txt_1.xsl" ?>
<!DOCTYPE catalog SYSTEM "cameras-catalog.dtd">

<catalog>
    <brand_info>
        <brand>Canon</brand>
        <realise_date>10.09.1937</realise_date>
    </brand_info>

    <cameras>
        <camera type="DSLR" resistance="dust-proof">

            <brand_info>
                <brand>Canon</brand>
                <realise_date>01.04.2017</realise_date>
            </brand_info>

            <model>EOS 800D</model>
            <price currency="лв"> 1200</price>
            <color>Черен</color>
            <image>camera_images/Canon_EOS_800D.jpg</image>

            <features>
                <effective_pixels px="мегапиксела"> 24 </effective_pixels>
                <wi-fi has="Yes"/>
                <processor>DIGIC 7</processor>
                <display>Clear View II TFT</display>
                <video max-duration="29:59">MP4 (видео: H.264 вътрекадрова / междукадрова компресия, звук: линеен PCM / AAC, нивото на записвания звук може да се настройва ръчно от потребителя)</video>
            </features>

            <physical-specifications>
                <size s_unit="mm"> 131,0 x 99,9 x 76,2</size>
                <weight w_unit="g">532</weight>
            </physical-specifications>

            <power_supply>
                <battery>Акумулаторна литиево-йонна батерия LP-E17</battery>
                <energy_saving>Захранването се изключва след 10/30 s</energy_saving>
                <charger>Захранващ адаптер AC-E6(N), DC съединител: DR-E18, Зарядно устройство LC-E17</charger>
            </power_supply>

        </camera>


        <camera type="Compact" resistance="dust-proof">

            <brand_info>
                <brand>Canon</brand>
                <realise_date>02.08.2019</realise_date>
            </brand_info>

            <model>PowerShot G7 X Mark III</model>
            <price currency="лв"> 1040</price>
            <color>Черен</color>
            <image>camera_images/canon-powershot-g7-x-mark-ii.jpg</image>

            <features>
                <effective_pixels px="мегапиксела"> 20 </effective_pixels>
                <wi-fi has="Yes"/>
                <processor>DIGIC 8</processor>
                <display>сензорен LCD (TFT)</display>
                <video max-duration="29:59">4K/HD/Full HD</video>
            </features>

            <physical-specifications>
                <size s_unit="mm">105,5 x 60,9 x 41,4</size>
                <weight w_unit="g">304</weight>
            </physical-specifications>

            <power_supply>
                <battery>Акумулаторна литиево-йонна батерия NB-13L</battery>
                <energy_saving>Няма</energy_saving>
                <charger> Зареждане чрез USB, достъпно с USB захранващ адаптер PD-E1</charger>
            </power_supply>

        </camera>


        <camera type="mirrorless" resistance="water-dust-proof">

            <brand_info>
                <brand>Canon</brand>
                <realise_date>07.12.2021</realise_date>
            </brand_info>

            <model>EOS R3</model>
            <price currency="лв"> 9740</price>
            <color>Черен</color>
            <image>camera_images/canon-eos-r3.jpg</image>

            <features>

                <effective_pixels px="мегапиксела"> 24 </effective_pixels>
                <wi-fi has="Yes"/>
                <processor>DIGIC X</processor>
                <display>Clear View LCD II</display>
                <video max-duration="6:00:00">MP4 видео/4K/Full HD/6K RAW</video>

            </features>

            <physical-specifications>
                <size s_unit="mm">150 x 142,6 x 87,2</size>
                <weight w_unit="g">822</weight>
            </physical-specifications>

            <power_supply>
                <battery>Акумулаторна литиево-йонна батерия LP-E19 </battery>
                <energy_saving>Изключване на захранването след 15 секунди, 30 секунди, 1, 3, 5, 10 или 30 минути</energy_saving>
                <charger> Зарядно устройство за батерии LC-E19E , AC адаптер AC-E19 и DC съединител DR-E19, PD-E1 USB захранващ адаптер</charger>
            </power_supply>


        </camera>

    </cameras>

</catalog>

=== bernasali/XML-Programming-Project/MyProject/new_xml_2.xml
<?xml version="1.0" encoding="utf-8"?>

<?xml-stylesheet type="txt/xsl" href="xml_xml_1.xsl" ?>
<!DOCTYPE catalog SYSTEM "cameras-catalog.dtd">

<catalog>

    <brand_info>
        <brand>Nikon</brand>
        <realise_date>25.07.1917</realise_date>
    </brand_info>

    <cameras>
        <camera type="mirrorless" resistance="dust-proof">

            <brand_info>
                <brand>Nikon</brand>
                <realise_date>23.12.2021</realise_date>
            </brand_info>

            <model>Z9</model>
            <price currency="лв">11 800</price>
            <color>Черен</color>
            <image>camera_images/nikon-z9.jpg</image>

            <features>

                <effective_pixels px="мегапиксела">46</effective_pixels>
                <wi-fi has="Yes"/>
                <processor>DIGIC X</processor>
                <display>сензорен TFT LCD с приблиз. 2 100 000 точки</display>
                <video max-duration="29:59">8K UHD/4K UHD</video>

            </features>

            <physical-specifications>
                <size s_unit="mm">149 x 149,5 x 90,5</size>
                <weight w_unit="g">1340</weight>
            </physical-specifications>

            <power_supply>
                <battery>Акумулаторна литиево-йонна батерия EN-EL18d</battery>
                <energy_saving>Захранването се изключва след 30 секунди, 1, 3, 5, 10 или 30 минути</energy_saving>
                <charger> Захранващ AC адаптер EH-7P; EH-6d; изисква конектор за захранването EP-6a</charger>
            </power_supply>

        </camera>


        <camera type="DSLR" resistance="dust-proof">

            <brand_info>
                <brand>Nikon</brand>
                <realise_date>06.01.2020</realise_date>
            </brand_info>

            <model>D780</model>
            <price currency="лв">4 500</price>
            <color>Черен</color>
            <image>camera_images/nikon-d780.jpg</image>

            <features>

                <effective_pixels px="мегапиксела">24</effective_pixels>
                <wi-fi has="Yes"/>
                <processor>AF-S обектив тип G с вграден процесор и бийонет F</processor>
                <display>сензорен TFT LCD дисплей с приблиз. 2 359 000 точки (XGA)</display>
                <video max-duration="50:59">4K UHD</video>

            </features>

            <physical-specifications>
                <size s_unit="mm">143,5 x 115,5 x 76</size>
                <weight w_unit="g">840</weight>
            </physical-specifications>

            <power_supply>
                <battery>Акумулаторна литиево-йонна батерия EN-EL15b</battery>
                <energy_saving>Захранването се изключва след 30 секунди, 1, 3, 5, 10 или 30 минути</energy_saving>
                <charger>Захранващ адаптер EH-5d/EH-5c/EH-5b; изисква конектор за захранването EP-5B </charger>
            </power_supply>


        </camera>

        <camera type="Compact" resistance="dust-proof">

            <brand_info>
                <brand>Nikon</brand>
                <realise_date>31.05.2017</realise_date>
            </brand_info>

            <model>COOLPIX W300</model>
            <price currency="лв">880</price>
            <color>Жълт</color>
            <image>camera_images/nikon-coolpix-w300-zhult-poda.jpg</image>

            <features>

                <effective_pixels px="мегапиксела">16</effective_pixels>
                <wi-fi has="Yes"/>
                <processor>AF-S обектив тип G с вграден процесор и бийонет F</processor>
                <display>7,5-сантиметров диагонал с приблизително 921 000 точки</display>
                <video max-duration="59:59">4K UHD</video>

            </features>

            <physical-specifications>
                <size s_unit="mm">111,5 x 66,0 x 29,0</size>
                <weight w_unit="g">231</weight>
            </physical-specifications>

            <power_supply>
                <battery>Акумулаторна литиево-йонна батерия EN-EL12</battery>
                <energy_saving>Захранването се изключва след  3, 5, 10 минути</energy_saving>
                <charger>Захранващ адаптер за зареждане на батерията във фотоапарата EH-73P </charger>
            </power_supply>


        </camera>




    </cameras>

</catalog>

=== bernasali/XML-Programming-Project/MyProject/new.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE catalog SYSTEM "cameras-catalog.dtd">

<catalog>
       <brand_info>
           <brand>Canon</brand>
           <realise_date>10.09.1937</realise_date>
       </brand_info>

    <cameras>
    <camera type="mirrorless" resistance="water-dust-proof">
        <brand_info>
            <brand>Canon</brand>
            <realise_date>09.07.2020</realise_date>

        </brand_info>
            <model>EOS R5</model>
            <price currency="лв"> 4200</price>
            <color>Черен</color>
            <image>Canon_EOS_R5.jpg</image>
        <features>

            <effective_pixels px="мегапиксела"> 45 </effective_pixels>
            <wi-fi has="Yes"/>
            <processor>DIGIC X</processor>
            <display>Clear View LCD II</display>
            <video max-duration="29:59">8K/4K/Full HD</video>

        </features>

            <physical-specifications>
                <size s_unit="mm"> 138,5 x 97,5 x 88</size>
                <weight w_unit="g">650</weight>

            </physical-specifications>
        <power_supply>
            <battery>Акумулаторна литиево-йонна батерия LP-E6NH</battery>
            <energy_saving>Захранването се изключва след 30 секунди, 1, 3, 5, 10 или 30 минути</energy_saving>
            <charger> Зарядно устройство за батерии LC-E6E (в комплекта), AC адаптер AC-E6N и DC съединител DR-E6</charger>
        </power_supply>


        </camera>

    </cameras>

</catalog>

=== bernasali/XML-Programming-Project/MyProject/new_xml_4.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE catalog SYSTEM "cameras-catalog.dtd">

<catalog>
    <brand_info>
        <brand>Nikon</brand>
        <realise_date>25.07.1917</realise_date>
    </brand_info>

    <cameras>
        <camera type="DSLR" resistance="dust-proof">
            <brand_info>
                <brand>Nikon</brand>
                <realise_date>24.08.2017</realise_date>

            </brand_info>
            <model>D850</model>
            <price currency="лв">5 299</price>
            <color>Черен</color>
            <image>camera_images/nikon-d850.jpg</image>

            <features>

                <effective_pixels px="мегапиксела">45</effective_pixels>
                <wi-fi has="Yes"/>
                <processor>AL</processor>
                <display>сензорен TFT LCD с приблизително 2 359 000 точки</display>
                <video max-duration="29:59">4K UHD</video>

            </features>

            <physical-specifications>
                <size s_unit="mm">146 x 124 x 78,5</size>
                <weight w_unit="g">1 005</weight>
            </physical-specifications>

            <power_supply>
                <battery>Акумулаторна литиево-йонна батерия EN-EL15b</battery>
                <energy_saving>Захранването се изключва след 1, 3, 5, 10 или 30 минути</energy_saving>
                <charger> Захранващ адаптер EH-5c/EH-5b; изисква конектор за захранването EP-5B </charger>
            </power_supply>


        </camera>


        <camera type="Compact" resistance="dust-proof">

            <brand_info>
                <brand>Nikon</brand>
                <realise_date>23.02.2016</realise_date>
            </brand_info>

            <model>COOLPIX B500</model>
            <price currency="лв">500</price>
            <color>Пурпурен</color>
            <image>camera_images/Nikon_COOLPIX B500.jpg</image>

            <features>

                <effective_pixels px="мегапиксела">16</effective_pixels>
                <wi-fi has="Yes"/>
                <processor>AF-S обектив тип G с вграден процесор и бийонет F</processor>
                <display>TFT LCD дисплей, с приблизително 921 000 точки</display>
                <video max-duration="1:30:00">H.264/MPEG-4 AVC</video>

            </features>

            <physical-specifications>
                <size s_unit="mm">113,5 x 78,3 x 94,9</size>
                <weight w_unit="g">542</weight>
            </physical-specifications>

            <power_supply>
                <battery>4 акумулаторни никел-метал-хидридни батерии EN-MH2</battery>
                <energy_saving>Захранването се изключва след 3, 5, 10 или 30 минути</energy_saving>
                <charger>захранващ адаптер EH-67/EH-67s</charger>
            </power_supply>


        </camera>

        <camera type="mirrorless" resistance="dust-proof">

            <brand_info>
                <brand>Nikon</brand>
                <realise_date>23.07.2021</realise_date>
            </brand_info>

            <model>Z fc</model>
            <price currency="лв">1999</price>
            <color>Черен/сребрист</color>
            <image>camera_images/nikon-z-fc.jpg</image>

            <features>

                <effective_pixels px="мегапиксела">20</effective_pixels>
                <wi-fi has="Yes"/>
                <processor>AF-S обектив тип G с вграден процесор и бийонет F</processor>
                <display>7сензорен TFT LCD с приблизително 1 040 000 точки</display>
                <video max-duration="59:59">4K UHD</video>

            </features>

            <physical-specifications>
                <size s_unit="mm">134,5 x 93,5 x 43,5 </size>
                <weight w_unit="g">545</weight>
            </physical-specifications>

            <power_supply>
                <battery>Акумулаторна литиево-йонна батерия EN-EL25</battery>
                <energy_saving>Захранването се изключва след  3, 5, 10 минути</energy_saving>
                <charger>Захранващ AC адаптер EH-7P </charger>
            </power_supply>


        </camera>


    </cameras>

</catalog>

=== bernasali/XML-Programming-Project/MyProject/new_xml_3.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet type="txt/xsl" href="xml_html_1.xsl" ?>

<!DOCTYPE catalog SYSTEM "cameras-catalog.dtd">

<catalog>
    <brand_info>
        <brand>Canon</brand>
        <realise_date>10.09.1937</realise_date>
    </brand_info>

    <cameras>
        <camera type="DSLR" resistance="dust-proof">
        <brand_info>
            <brand>Canon</brand>
            <realise_date>18.07.2016</realise_date>

        </brand_info>
        <model>EOS 2000D</model>
        <price currency="лв">839</price>
        <color>Черен</color>
        <image>camera_images/Canon_EOS_2000D.jpg</image>
        <features>

            <effective_pixels px="мегапиксела"> 24 </effective_pixels>
            <wi-fi has="Yes"/>
            <processor>DIGIC 4+</processor>
            <display>TFT LCD, приблизително 920 000 точки</display>
            <video max-duration="29:59">MOV</video>

        </features>

        <physical-specifications>
            <size s_unit="mm"> 129,0 x 101,3 x 77,6</size>
            <weight w_unit="g">475</weight>

        </physical-specifications>
        <power_supply>
            <battery>Акумулаторна литиево-йонна батерия LP-E10</battery>
            <energy_saving>Захранването се изключва след 30 секунди, 1, 3, 5, 10 или 30 минути</energy_saving>
            <charger>Зарядно устройство LC-E10E, компактен захранващ адаптер CA-PS700, DC съединител DR-E10</charger>
        </power_supply>


    </camera>

        <camera type="mirrorless" resistance="dust-proof">

            <brand_info>
                <brand>Canon</brand>
                <realise_date>05.11.2021</realise_date>
            </brand_info>

            <model>EOS M50 Mark II</model>
            <price currency="лв">1349</price>
            <color>Черен</color>
            <image>camera_images/Canon EOS M50 Mark II.jpg</image>
            <features>

                <effective_pixels px="мегапиксела"> 24 </effective_pixels>
                <wi-fi has="Yes"/>
                <processor>DIGIC 8</processor>
                <display>сензорен LCD (TFT) дисплей с приблизително 1 040 000 точки</display>
                <video max-duration="29:59">4K/Full HD/HD</video>

            </features>

            <physical-specifications>
                <size s_unit="mm">116,3 x 88,1 x 58,7</size>
                <weight w_unit="g">387</weight>
            </physical-specifications>

            <power_supply>
                <battery>Акумулаторна литиево-йонна батерия LP-E12</battery>
                <energy_saving>Захранването се изключва след 30 секунди, 1, 3, 5, 10 или 30 минути</energy_saving>
                <charger>Зарядно устройство за батерии LC-E12,компактен захранващ адаптер CA-PS700, DC съединител DR-E12</charger>
            </power_supply>


        </camera>

    </cameras>

</catalog>
